Repository pinecone-studio/pinecone-intern-monorepo, pull requests merged in 2024-12, with the labels that each got.

#2568 feat('hotel-booking-frontend'): 'added booking.graphql'
  apps/L1AB/hotel-booking/frontend/src/graphql/booking.graphql
Labels: PR status: code ready

#2578 2545 dagasan humuusiinhee postiig avah be
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/mutations/followers/create-followers.spec.ts
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/post/get-posts-by-followers-id.spec.ts
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/story/get-all-stories.spec.ts
  apps/L1AB/Instagram/instagram-backend/src/models/story-model.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/followers/create-followers.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/save/create-save.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/post/get-posts-by-followers-id.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/post/index.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/story/get-all-stories.ts
  apps/L1AB/Instagram/instagram-backend/src/schemas/followers.schema.ts
  apps/L1AB/Instagram/instagram-backend/src/schemas/posts.schema.ts
  apps/L1AB/Instagram/instagram-backend/src/schemas/story.schema.ts
Labels: PR status: code ready

#2581 feat(ig-be): zuvhun dagadag humuusiinhe post-g harna
  apps/L1AB/Instagram/instagram-frontend/specs/components/NewsFeed.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/NewsFeed.tsx
  apps/L1AB/Instagram/instagram-frontend/src/graphql/followers.graphql
  apps/L1AB/Instagram/instagram-frontend/src/graphql/post.graphql
Labels: PR status: code ready

#2584 feat(hotel-booking-frontend): main client error fix
  apps/L1AB/hotel-booking/frontend/src/app/(public)/(home)/layout.tsx
  apps/L1AB/hotel-booking/frontend/src/app/(public)/(home)/page.tsx
  apps/L1AB/hotel-booking/frontend/src/app/global.css
Labels: PR status: code ready

#2586 fix: [BE] refactor getfollowers and getfollowing
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/followers/get-followers-by-id-query.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/followers/get-following-by-id-query.ts
Labels: PR status: code ready, 1ab-team3, backend

#2564 feat(concert-ticket-booking ticket-frontend): [FE] admin dashboard na…
  apps/L1AB/concert-ticket-booking/frontend/specs/components/adminspecs/AdminNavbar.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AdminNavbar.tsx
Labels: PR status: code ready

#2587 feat(concert-ticket-booking frontend): userprofile fixed
  apps/L1AB/concert-ticket-booking/backend/src/resolvers/mutations/user/update-user.mutation.ts
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-Black.woff
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-Black.woff2
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-Bold.woff
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-Bold.woff2
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-ExtraBold.woff
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-ExtraBold.woff2
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-Heavy.woff
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-Heavy.woff2
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-Light.woff
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-Light.woff2
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-Medium.woff
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-Medium.woff2
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-Regular.woff
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-Regular.woff2
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-SemiBold.woff
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-SemiBold.woff2
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-Thin.woff
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-Thin.woff2
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-UltraLight.woff
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/GIP-UltraLight.woff2
  apps/L1AB/concert-ticket-booking/frontend/public/fonts/GIP/index.ts
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/UserProfile.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/app/global.css
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/SearchPageComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/UserProfile.tsx
  apps/L1AB/concert-ticket-booking/frontend/tailwind.config.js
Labels: PR status: code ready

#2566 feat(concert-ticket-booking): cancel button logic fixed
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/UserHistory.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/UserHistory.tsx
Labels: PR status: code ready

#2589 feat(ig-be): savedpost query
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/saved/get-all-saved-post.spec.ts
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/saved/get-saved-by-postid.spec.ts
  apps/L1AB/Instagram/instagram-backend/src/models/saved-model.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/save/get-all-saved-post.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/save/get-saved-by-postid.ts
  apps/L1AB/Instagram/instagram-backend/src/schemas/saved.schema.ts
  apps/L1AB/Instagram/instagram-frontend/specs/components/PostCardLikeSection.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCardLikeSection.tsx
  apps/L1AB/Instagram/instagram-frontend/src/graphql/saved.graphql
Labels: PR status: code ready

#2597 feat: [FE] profile page followers && following hargddag remove && uur…
  apps/L1AB/Instagram/instagram-frontend/specs/components/FollowersDialog.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/FollowersDialogRemove.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/FollowingButton.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/ProfilePagePosts.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/ProfilePagePostsAndSaved.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/ProfilePagePrivate.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/ProfilePageTop.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/ProfilePostsSection.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/RemoveFollowersDialog.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/(main)/profile/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/FollowersDialog.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/FollowersDialogRemove.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/FollowingButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePageFirstPost.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePagePosts.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePagePostsAndSaved.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePagePrivate.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePageTop.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePostsSection.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/RemoveFollowersDialog.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/providers/UserProvider.tsx
  apps/L1AB/Instagram/instagram-frontend/src/graphql/followers.graphql
Labels: PR status: code ready, 1ab-team3, backend

#2590 feat: main-Layout, main-3folder
  apps/L1AB/hotel-booking/frontend/specs/components/main/CheckingQpay.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/Footer.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/Header.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/assets/CheckingConfirm.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/app/(main)/(checkout)/checkconfirm/page.tsx
  apps/L1AB/hotel-booking/frontend/src/app/(main)/(checkout)/checkingqpay/page.tsx
  apps/L1AB/hotel-booking/frontend/src/app/(main)/(checkout)/checkouthome/page.tsx
  apps/L1AB/hotel-booking/frontend/src/app/(main)/bookings/[booking]/page.tsx
  apps/L1AB/hotel-booking/frontend/src/app/(main)/layout.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/CheckingConfirm.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/CheckingQpay.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/CheckoutHome.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/Footer.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/Header.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/index.ts
Labels: 1ab-team3

#2594 feat: booking component-update
  apps/L1AB/hotel-booking/frontend/src/app/(main)/bookings/page.tsx
  apps/L1AB/hotel-booking/frontend/src/app/(main)/bookings/previousBooking/page.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/BookingConfirmedBooking.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/BookingEmptyState.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/CheckoutHome.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/PrevoiusBooking.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/assets/BookingSvg.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/assets/index.ts
Labels: PR status: code ready

#2600 fix(hotel-booking-frontenf): icons change
  apps/L1AB/hotel-booking/frontend/specs/components/admin/assets/DetailsUpcomingBooking.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/GuestsTable.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/room-details/RoomDetailsUpcomingBookings.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/BookingConfirmedBooking.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/BookingEmptyState.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/CheckoutHome.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/Loading.tsx
Labels: PR status: code ready

#2602 fix: [BE] refactor login
  apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/auth/login.ts
  apps/L1AB/Instagram/instagram-backend/src/schemas/user-schema.ts
Labels: PR status: code ready, 1ab-team3, backend

#2605 fix: [FE] decode token refactor
  apps/L1AB/Instagram/instagram-frontend/cypress/e2e/(public)/login/index.cy.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/DecodeUtils.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/(public)/login/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/providers/UserProvider.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/utils/decode-utils.ts
  apps/L1AB/Instagram/instagram-frontend/src/graphql/all.graphql
Labels: PR status: code ready, 1ab-team3, frontend

#2607 feat(ticket booking): pagination-logic
  apps/L1AB/concert-ticket-booking/frontend/specs/components/adminspecs/AdminDashboardContainer.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/adminspecs/AdminPagination.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AdminDashPagination.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AdminDashboard.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/UpdateEventComponent.tsx
Labels: PR status: code ready

#2604 feat(concert-ticket-booking ticket-frontend): [FE] admin artist ui
  apps/L1AB/concert-ticket-booking/frontend/cypress/e2e/admin/artist/index.cy.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/adminspecs/AddArtistComponent.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/adminspecs/ArtistComponent.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/app/admin/artist/page.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AddArtistComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/ArtistComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/index.ts
  apps/L1AB/concert-ticket-booking/frontend/src/graphql/artist.graphql
Labels: PR status: code ready

#2595 2593 fe stage style fix
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/StageStyle.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/assets/icons/LeftBottomOut.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/assets/icons/LeftTopOut.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/assets/icons/RightBottomOut.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/assets/icons/RightTopOut.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/assets/icons/TopSmallMiddle.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/assets/icons/index.ts
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/StageStyle.tsx
Labels: PR status: code ready

#2608 feat(ig-[be]): like notifications
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/mutations/likes/create-like.spec.ts
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/notifications/get-notifications-by-user-id.spec.ts
  apps/L1AB/Instagram/instagram-backend/src/models/notifications-model.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/likes/create-like.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/index.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/notificiations/get-notifications-by-user-id.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/notificiations/index.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/save/get-saved-by-postid.ts
  apps/L1AB/Instagram/instagram-backend/src/schemas/notifications.schema.ts
Labels: PR status: code ready

#2610 feat(ig-be): get notify
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/notifications/get-notifications-by-user-id.spec.ts
  apps/L1AB/Instagram/instagram-backend/src/models/notifications-model.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/notificiations/get-notifications-by-user-id.ts
  apps/L1AB/Instagram/instagram-backend/src/schemas/notifications.schema.ts
Labels: PR status: code ready

#2613 fix: [FE] refactor
  apps/L1AB/Instagram/instagram-frontend/cypress/e2e/(public)/login/index.cy.tsx
  apps/L1AB/Instagram/instagram-frontend/next.config.js
  apps/L1AB/Instagram/instagram-frontend/specs/components/DecodeUtils.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/(public)/login/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/providers/UserProvider.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/utils/decode-utils.ts
Labels: PR status: code ready, 1ab-team3, frontend

#2615 2222 fe show comments component
  apps/L1AB/Instagram/instagram-frontend/cypress/e2e/(main)/home/index.cy.tsx
  apps/L1AB/Instagram/instagram-frontend/project.json
  apps/L1AB/Instagram/instagram-frontend/specs/components/PostCardLikeSection.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/PostDetail.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/NewsFeed.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCard.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCardCommentSection.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCardLikeSection.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostDetail.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/RightSideBar.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/assets/icons/HeartIcon.tsx
  apps/L1AB/Instagram/instagram-frontend/src/graphql/comments.graphql
  apps/L1AB/Instagram/instagram-frontend/src/graphql/saved.graphql
  libs/shadcn/src/lib/ui/dialog.tsx
Labels: PR status: code ready, 1ab-team3, frontend

#2580 2371 fe editprofile dahin zasvarlav
  apps/L1AB/Instagram/instagram-frontend/specs/components/EditProfile.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/(main)/editprofile/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/EditProfile.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePageTop.tsx
  apps/L1AB/Instagram/instagram-frontend/src/graphql/UpdateUser.graphql
  apps/L1AB/Instagram/instagram-frontend/src/graphql/followers.graphql
Labels: PR status: code ready

#2617 feat(concert-ticket-booking be fe): signin signup validate added
  apps/L1AB/concert-ticket-booking/backend/specs/resolvers/mutations/user/sign-in-user.spec.ts
  apps/L1AB/concert-ticket-booking/backend/src/resolvers/mutations/user/sign-in-user.mutation.ts
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/SignUp.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/EventDetails.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/FormInput.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/PasswordInput.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/SignUp.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/UserProfile.tsx
Labels: PR status: code ready

#2620 feat: [FE] add logout dialog
  apps/L1AB/Instagram/instagram-frontend/cypress/utils/all-pages.json
  apps/L1AB/Instagram/instagram-frontend/specs/components/EditProfile.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/RightSideBar.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/EditProfile.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/LogoutButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/RightSideBar.tsx
Labels: PR status: code ready, 1ab-team3, frontend

#2616 add-the-mutation-which-check-the-otp
  apps/L1AB/hotel-booking/backend/specs/resolvers/mutations/user/sign-up-check-otp.spec.ts
  apps/L1AB/hotel-booking/backend/specs/resolvers/mutations/user/sign-up-send-otp.spec.ts
  apps/L1AB/hotel-booking/backend/specs/resolvers/mutations/user/sign-up.spec.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/mutations/user/sign-in.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/mutations/user/sign-up-check-otp.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/mutations/user/sign-up.ts
  apps/L1AB/hotel-booking/backend/src/schemas/user.schema.ts
Labels: PR status: code ready, backend

#2623 feat: [FE] add Loading component and add pages
  apps/L1AB/Instagram/instagram-frontend/specs/components/ProfilePagePosts.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/(main)/profile/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/FollowingButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/Loading.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/NewsFeed.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePagePosts.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePageTop.tsx
Labels: PR status: code ready, 1ab-team3, frontend

#2627 fix('hotel-booking-backend'): 'added user to booking'
  apps/L1AB/hotel-booking/backend/specs/resolvers/mutations/booking/create-booking.spec.ts
  apps/L1AB/hotel-booking/backend/src/models/booking-model.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/queries/booking/get-all-bookings.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/queries/booking/get-booking-by-id.ts
  apps/L1AB/hotel-booking/backend/src/schemas/booking.schema.ts
Labels: PR status: code ready

#2634 fix: fix loading
  apps/L1AB/Instagram/instagram-frontend/specs/components/PageLoading.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/layout.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/FollowingButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/Loading.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/NewsFeed.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PageLoading.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePagePosts.tsx
Labels: PR status: code ready, 1ab-team3, frontend

#2625 2464 be create hotel update
  apps/L1AB/hotel-booking/frontend/specs/components/admin/GuestInfo.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/HotelDetails.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/LocationDialog.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/assets/DetailsCard.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/assets/DetailsContainer.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/assets/DetailsLeft.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/assets/DetailsRight.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/assets/HotelDetailsGeneralInfo.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/assets/HotelDetailsLocation.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/dialogs/HotelGeneralInfoDailog.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/dialogs/LocationDialog.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/SignUpForm.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/SignUpFormPasswordStep.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/app/admin/layout.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/GuestInfo.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/HotelDetails.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/RoomDetails.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/DetailsContainer.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/hotel-details/HotelDetailsAboutThisProperty.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/hotel-details/HotelDetailsAmenities.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/hotel-details/HotelDetailsFrequently.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/hotel-details/HotelDetailsGeneralInfo.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/hotel-details/HotelDetailsImages.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/hotel-details/HotelDetailsLocation.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/hotel-details/HotelDetailsPolicies.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/hotel-details/HotelDetailsPolicies2.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/hotel-details/HotelDetailsRoomTypes.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/hotel-details/HotelDetailsUpcomingBookings.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/dialogs/HotelGeneralInfoDialog.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/dialogs/LocationDialog.tsx
  apps/L1AB/hotel-booking/frontend/src/components/icon/NotImagesIcon.tsx
  apps/L1AB/hotel-booking/frontend/src/components/icon/index.ts
  apps/L1AB/hotel-booking/frontend/src/components/main/SignUpFormPasswordStep.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/assets/BookingSvg.tsx
  apps/L1AB/hotel-booking/frontend/src/components/providers/AdminProvider.tsx
Labels: PR status: code ready

#2636 refactor(concert ticket): show the number of remaining seats in the s…
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/StageStyle.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/BookTicket.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/StageStyle.tsx
Labels: PR status: code ready

#2641 feat: fix cd
  .github/workflows/cd.yml
Labels: PR status: code ready

#2639 feat(concert-ticket-booking frontend): darkMode
  apps/L1AB/concert-ticket-booking/frontend/cypress/e2e/(main)/profile/index.cy.tsx
  apps/L1AB/concert-ticket-booking/frontend/public/Concert hall plan.png
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/MainNavbar.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/MainNavbarLightTrue.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/app/(main)/layout.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/app/(main)/profile/page.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/app/global.css
  apps/L1AB/concert-ticket-booking/frontend/src/app/layout.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/BookTicket.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/Container.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/Event.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/EventCard.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/EventDetails.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/ForgetPassword.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/ForgetPasswordEyeInputs.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/FormInput.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/MainFooter.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/MainHero.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/MainNavbar.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/OrderCheckout.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/PasswordInput.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/PasswordRecovery.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/Payment.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/RecoveryEmail.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/RelatedEvents.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/SearchPageComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/SignIn.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/SignUp.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/Skeletons/EventCardSkeleton.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/Skeletons/EventDetailsSkeleton.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/Skeletons/RelatedEventsSkeleton.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/UserHistory.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/UserHistoryDialog.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/UserProfile.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/providers/ApolloWrapper.tsx
  apps/L1AB/concert-ticket-booking/frontend/tailwind.config.js
Labels: PR status: code ready

#2643 feat: get hotel by id amenities
  apps/L1AB/hotel-booking/backend/specs/resolvers/queries/hotelAmenities/get-hotel-id-by-hotel-amenities.spec.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/queries/hotel-amenities/get-hotel-amenity-by-id.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/queries/hotel-amenities/get-hotel-id-by-hotel-amenities.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/queries/hotel-amenities/index.ts
  apps/L1AB/hotel-booking/backend/src/schemas/hotel-ameneties.schema.ts
Labels: PR status: code ready, backend

#2644 fix(concert-ticket-booking ticket-backend): [BE] artist image deleted
  apps/L1AB/concert-ticket-booking/backend/src/models/artist-model.ts
  apps/L1AB/concert-ticket-booking/backend/src/resolvers/mutations/artist/update-artist.ts
  apps/L1AB/concert-ticket-booking/backend/src/schemas/artist.schema.ts
Labels: PR status: code ready

#2647 feat: fix cd
  .github/workflows/cd.yml
Labels: PR status: code ready

#2650 feat(ticket-booking): artist and order changed
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/OrderCheckout.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AddEventComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AdminDash.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/OrderCheckout.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/graphql/artist.graphql
Labels: PR status: code ready

#2652 feat: icon added
  apps/L1AB/hotel-booking/backend/specs/resolvers/mutations/amenity/create-amenity.spec.ts
  apps/L1AB/hotel-booking/backend/specs/resolvers/mutations/amenity/update-amenity.spec.ts
  apps/L1AB/hotel-booking/backend/src/models/amenity-model.ts
  apps/L1AB/hotel-booking/backend/src/models/hotel-ameneties.model.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/queries/hotel-amenities/get-hotel-id-by-hotel-amenities.ts
  apps/L1AB/hotel-booking/backend/src/schemas/amenity.schema.ts
  apps/L1AB/hotel-booking/backend/src/schemas/hotel-ameneties.schema.ts
Labels: PR status: code ready, backend

#2653 feat: previous Booking Salgav
  apps/L1AB/hotel-booking/frontend/specs/components/main/BookingCard.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/NoPreviousBooking.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/PreviousBooking.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/StartBooking.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/app/(main)/(checkout)/checkconfirm/page.tsx
  apps/L1AB/hotel-booking/frontend/src/app/(main)/bookings/page.tsx
  apps/L1AB/hotel-booking/frontend/src/app/(main)/bookings/previousBooking/page.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/BookingCard.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/BookingConfirmedBooking.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/NoPreviousBooking.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/PrevoiusBooking.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/StartBooking.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/index.ts
Labels: PR status: code ready

#2654 feat(ig-be): saved mutation zasav
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/mutations/save/create-save.spec.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/save/create-save.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/save/index.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/save/get-saved-by-postid.ts
  apps/L1AB/Instagram/instagram-backend/src/schemas/saved.schema.ts
Labels: PR status: code ready, 1ab-team3, backend

#2658 fix: fix saved mutantion
  apps/L1AB/Instagram/instagram-frontend/src/graphql/saved.graphql
Labels: PR status: code ready, 1ab-team3, frontend

#2659 feat(concert-ticket-booking frontend): middleware and ui added
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/Event.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/RelatedEvents.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/SearchPageComponent.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/mock.ts
  apps/L1AB/concert-ticket-booking/frontend/src/app/(main)/layout.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/app/layout.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AdminNavbar.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/Event.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/EventCard.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/EventDetails.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/MainNavbar.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/RelatedEvents.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/SearchPageComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/UserProfile.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/providers/AuthProvider.tsx
Labels: PR status: code ready

#2651 feat(fe): editprofile hiisen
  apps/L1AB/Instagram/instagram-frontend/jest.config.ts
  apps/L1AB/Instagram/instagram-frontend/specs/components/EditProfile.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/EditProfile.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/FollowingButton.tsx
Labels: PR status: code ready

#2663 feat(i): install-lib
  package.json
  yarn.lock
Labels: PR status: code ready

#2661 2263 fe story
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/story/get-all-stories.spec.ts
  apps/L1AB/Instagram/instagram-backend/src/schemas/story.schema.ts
  apps/L1AB/Instagram/instagram-frontend/public/LogoWhite.png
  apps/L1AB/Instagram/instagram-frontend/specs/components/Story.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/StoryCard.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/StoryDetail.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/StoryDetail2.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/StoryNull.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/UserStory.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/(main)/home/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/(main)/layout.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/(main)/story/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/Story.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/StoryCard.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/StoryDetail.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/UserStory.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/providers/StoryProvider.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/providers/index.ts
  apps/L1AB/Instagram/instagram-frontend/src/graphql/story.graphql
Labels: PR status: code ready

#2557 feat(hotel-booking frontend): hotel detail choose room
  apps/L1AB/hotel-booking/frontend/specs/components/main/HotelDetails.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/assets/HotelamenitiesMock.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/assets/ImagesDialog.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/assets/mock1.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/HotelDetails.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/assets/HotelamenitiesMock.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/assets/RoomCard.tsx
Labels: PR status: code ready

#2665 2631 fe update artist logic
  apps/L1AB/concert-ticket-booking/frontend/specs/components/adminspecs/AddArtistComponent.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/adminspecs/ArtistComponent.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AddArtistComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/ArtistComponent.tsx
Labels: PR status: code ready

#2664 2215 fe password recovery logic
  apps/L1AB/concert-ticket-booking/frontend/cypress/e2e/(main)/(auth)/recovery/checkpoint/index.cy.tsx
  apps/L1AB/concert-ticket-booking/frontend/cypress/e2e/(main)/(auth)/recovery/index.cy.tsx
  apps/L1AB/concert-ticket-booking/frontend/cypress/e2e/(main)/(auth)/recovery/otpInput/index.cy.tsx
  apps/L1AB/concert-ticket-booking/frontend/cypress/e2e/(main)/(auth)/recovery/passwordRecovery/index.cy.tsx
  apps/L1AB/concert-ticket-booking/frontend/cypress/utils/all-pages.json
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/PasswordRecovery.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/RecoveryEmail.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/RecoveryEmailLoadinFalse.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/VerifyOtp.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/VerifyOtpTimer.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/app/(main)/(auth)/recovery/checkpoint/page.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/app/(main)/(auth)/recovery/otpInput/page.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/app/(main)/(auth)/recovery/page.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/app/(main)/(auth)/recovery/passwordRecovery/page.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/PasswordRecovery.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/RecoveryEmail.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/SignIn.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/VerifyOtp.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/VerifyOtpTimer.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/index.ts
  apps/L1AB/concert-ticket-booking/frontend/src/components/providers/AuthProvider.tsx
Labels: PR status: code ready

#2666 feat(hotel-booking-frontend): remove hotelname dialog
  apps/L1AB/hotel-booking/frontend/specs/components/admin/HotelsTable.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/dialogs/HotelNameDialog.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/HotelsTable.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/dialogs/HotelNameDialog.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/dialogs/index.ts
  apps/L1AB/hotel-booking/frontend/src/components/icon/PlusIcon.tsx
  apps/L1AB/hotel-booking/frontend/src/components/icon/index.ts
Labels: PR status: code ready

#2668 feat: [BE] create follow with notification
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/mutations/followers/create-followers.spec.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/followers/create-followers.ts
  apps/L1AB/Instagram/instagram-backend/src/schemas/notifications.schema.ts
Labels: PR status: code ready, 1ab-team3, backend

#2670 feat: [FE] show saved posts & post card userid & layout refactor
  apps/L1AB/Instagram/instagram-frontend/specs/components/PostCard.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/ProfilePostsSection.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/(main)/layout.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/NewsFeed.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCard.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostDetail.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePostsSection.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/StoryCard.tsx
  apps/L1AB/Instagram/instagram-frontend/src/graphql/saved.graphql
Labels: PR status: code ready, 1ab-team3, frontend

#2672 fix: fe story card color change
  apps/L1AB/Instagram/instagram-frontend/src/app/(main)/home/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/(main)/story/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/EditProfile.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/Story.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/StoryCard.tsx
Labels: PR status: code ready, 1ab-team3, frontend

#2676 feat([fe]-ig): saveButton
  apps/L1AB/Instagram/instagram-frontend/specs/components/PostCardLikeSection.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCardLikeSection.tsx
  apps/L1AB/Instagram/instagram-frontend/src/graphql/saved.graphql
Labels: PR status: code ready

#2679 feat(hotel-booking-backend): 'added get booking by user id'
  apps/L1AB/hotel-booking/backend/specs/resolvers/queries/booking/get-booking-by-user-id.spec.ts
  apps/L1AB/hotel-booking/backend/src/models/booking-model.ts
  apps/L1AB/hotel-booking/backend/src/models/user-model.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/queries/booking/get-booking-by-user-id.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/queries/booking/index.ts
  apps/L1AB/hotel-booking/backend/src/schemas/booking.schema.ts
Labels: PR status: code ready

#2683 perf(concert-ticket-booking-backend): refactor nodemailer
  apps/L1AB/concert-ticket-booking/backend/next.config.js
  apps/L1AB/concert-ticket-booking/backend/src/library/nodemailer.ts
  apps/L1AB/concert-ticket-booking/backend/src/resolvers/mutations/user/request-password-recovery.mutation.ts
Labels: PR status: code ready

#2685 feat(hotel-booking-frontend): 'added upload photo dialog comp
  apps/L1AB/hotel-booking/frontend/specs/components/admin/UploadPhoto.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/UploadPhoto.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/index.ts
Labels: PR status: code ready

#2686 feat(instgram): create-post
  apps/L1AB/Instagram/instagram-frontend/cypress/e2e/(main)/home/index.cy.tsx
  apps/L1AB/Instagram/instagram-frontend/cypress/e2e/(main)/profile/index.cy.tsx
  apps/L1AB/Instagram/instagram-frontend/cypress/utils/all-pages.json
  apps/L1AB/Instagram/instagram-frontend/jest.config.ts
  apps/L1AB/Instagram/instagram-frontend/specs/components/CreateButton.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/CreatePostCancelButton.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/CreatePostDescription.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/CreatePostUpload.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/UploadIcon.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/CreateButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/CreatePost.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/CreatePostCancelButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/CreatePostDescription.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/CreatePostUpload.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/CreateStory.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/icon/UploadIcon.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/providers/UserProvider.tsx
  apps/L1AB/Instagram/instagram-frontend/src/graphql/mutation.graphql
Labels: PR status: code ready, 1ab-team3

#2690 2611 like notify fe deer avchrah
  apps/L1AB/Instagram/instagram-backend/src/schemas/notifications.schema.ts
  apps/L1AB/Instagram/instagram-frontend/specs/components/NotificationDrawer.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/Notifications.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/PostCard.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/utils/date-utils.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/NotificationDrawer.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/Notifications.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/UsersMap.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/notificationComps/EarlierNotifications.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/notificationComps/TodayNotifications.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/notificationComps/YesterdayNotifications.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/providers/UserProvider.tsx
  apps/L1AB/Instagram/instagram-frontend/src/graphql/notify.graphql
  apps/L1AB/Instagram/instagram-frontend/src/utils/date-utils.ts
Labels: PR status: code ready

#2691 feat(package.json yarn.lock): add qr generator setup
  package.json
  yarn.lock
Labels: PR status: code ready

#2694 feat: booooking Details 2 salgav
  apps/L1AB/hotel-booking/frontend/specs/components/main/BookingDetailRoom.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/BoookingDetailBooked.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/app/(main)/bookings/[booking]/page.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/BookingDetailBooked.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/BookingDetailRoom.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/BookingDetails.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/index.ts
Labels: PR status: code ready

#2699 fix(concert-ticket-booking): booking bug fixed
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/BookTicket.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/BookTicket.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/UserHistory.tsx
Labels: PR status: code ready

#2704 feat: [FE] uur user iin followers orood dagah unfollow hiih
  apps/L1AB/Instagram/instagram-frontend/specs/components/FollowersDialog.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/FollowersDialogRemove.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/FollowersDialogRemove.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePageTop.tsx
Labels: PR status: code ready, 1ab-team3, frontend

#2708 2472 be send qr to email
  apps/L1AB/concert-ticket-booking/backend/specs/resolvers/mutations/booking/send-qr-to-email.spec.ts
  apps/L1AB/concert-ticket-booking/backend/src/library/nodemailer.ts
  apps/L1AB/concert-ticket-booking/backend/src/models/index.ts
  apps/L1AB/concert-ticket-booking/backend/src/models/qr-model.ts
  apps/L1AB/concert-ticket-booking/backend/src/resolvers/mutations/booking/index.ts
  apps/L1AB/concert-ticket-booking/backend/src/resolvers/mutations/booking/send-qr-to-email.ts
  apps/L1AB/concert-ticket-booking/backend/src/schemas/index.ts
  apps/L1AB/concert-ticket-booking/backend/src/schemas/qr.schema.ts
Labels: PR status: code ready

#2702 feat(concert-ticket): booking vsrelt done
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/UserHistory.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/UserHistory.tsx
Labels: PR status: code ready

#2693 feat(concert-ticket-booking frontend): fixed
  apps/L1AB/concert-ticket-booking/frontend/cypress/utils/all-pages.json
  apps/L1AB/concert-ticket-booking/frontend/specs/components/adminspecs/ArtistComponent.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/app/admin/layout.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AddArtistComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AddEventComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AdminDashPagination.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AdminDashboardSearcher.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AdminNavbar.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/ArtistComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/providers/AuthProvider.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/providers/Middleware.tsx
Labels: PR status: code ready

#2709 feat: check Out Home salgav
  apps/L1AB/hotel-booking/frontend/specs/components/main/CheckingBookingLeft.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/CheckingBookingRight.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/CheckingBookingLeft.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/CheckingBookingRight.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/index.ts
Labels: PR status: code ready

#2712 feat: bE room amenity nemsen
  apps/L1AB/hotel-booking/backend/specs/resolvers/mutations/room/create-room.spec.ts
  apps/L1AB/hotel-booking/backend/specs/resolvers/queries/room/get-room-by-id.spec.ts
  apps/L1AB/hotel-booking/backend/src/models/room-model.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/queries/room/get-room-by-id.ts
  apps/L1AB/hotel-booking/backend/src/schemas/room.schema.ts
Labels: PR status: code ready, backend

#2716 2715 be fix send qr to email mutation
  apps/L1AB/concert-ticket-booking/backend/src/resolvers/mutations/booking/send-qr-to-email.ts
Labels: PR status: code ready

#2711 fix(concert-ticket-booking-backend): fix request password recovery te…
  apps/L1AB/concert-ticket-booking/backend/specs/resolvers/mutations/user/request-password-recovery.spec.ts
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/SearchPageComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/providers/Middleware.tsx
Labels: PR status: code ready

#2721 fix: [FE] fix postdetail
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCard.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCardLikeSection.tsx
Labels: PR status: code ready, 1ab-team3, frontend

#2722 feat(concert-ticket-booking-frontend): add send qr to email logic
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/Payment.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/Payment.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/graphql/qr.graphql
Labels: PR status: code ready

#2724 2717 fe be admin securty
  apps/L1AB/concert-ticket-booking/frontend/cypress/e2e/(main)/(auth)/signin/index.cy.tsx
  apps/L1AB/concert-ticket-booking/frontend/cypress/e2e/admin/artist/index.cy.tsx
  apps/L1AB/concert-ticket-booking/frontend/cypress/e2e/admin/cancel/index.cy.tsx
  apps/L1AB/concert-ticket-booking/frontend/cypress/e2e/admin/index.cy.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/MainNavbarLightTrue.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AdminNavbar.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/MainNavbar.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/providers/ApolloWrapper.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/providers/Middleware.tsx
Labels: PR status: code ready

#2725 feat(hotel-booking-frontend): image use
  apps/L1AB/hotel-booking/frontend/specs/components/admin/HotelDetails.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/RoomDetails.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/UploadPhoto.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/assets/hotel-details/HotelDetailsImages.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/assets/hotel-details/HotelDetailsRoomTypes.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/RoomDetails.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/UploadPhoto.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/hotel-details/HotelDetailsImages.tsx
  apps/L1AB/hotel-booking/frontend/src/components/providers/AdminProvider.tsx
Labels: PR status: code ready

#2714 feat(hotel booking frontend): filter-hotels
  apps/L1AB/hotel-booking/frontend/specs/components/main/FilterHotels.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/FilterHotels.tsx
  apps/L1AB/hotel-booking/frontend/src/graphql/hotelamenities.graphql
Labels: PR status: code ready

#2726 fix(ticket booking): user apollowrapper fixed
  apps/L1AB/concert-ticket-booking/frontend/src/components/providers/ApolloWrapper.tsx
Labels: PR status: code ready

#2732 feat(hotel-booking-backend): added get available rooms query
  apps/L1AB/hotel-booking/backend/specs/resolvers/queries/room/get-available-rooms.spec.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/queries/room/get-available-rooms.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/queries/room/index.ts
  apps/L1AB/hotel-booking/backend/src/schemas/room.schema.ts
Labels: PR status: code ready

#2735 feat(ig-fe): jijig zasvarud
  apps/L1AB/Instagram/instagram-frontend/src/app/(main)/home/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/(main)/layout.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/(main)/profile/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/LeftSideBar.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCard.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePageFirstPost.tsx
Labels: PR status: code ready

#2738 feat(concert-ticket-booking): text fixed
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AddEventComponent.tsx
Labels: PR status: code ready

#2739 feat(concert-ticket-booking frontend): close button fixed
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/UpdateEventComponent.tsx
Labels: PR status: code ready

#2742 feat(concert-ticket): bookings table
  apps/L1AB/concert-ticket-booking/frontend/specs/components/adminspecs/AdminNavbar.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/adminspecs/BookingsComponent.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/app/admin/bookings/page.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AdminNavbar.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/BookingComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/CancelComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/EventDetails.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/OrderCheckout.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/Payment.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/providers/Middleware.tsx
Labels: PR status: code ready

#2743 feat: fe-user-booking-connection
  apps/L1AB/hotel-booking/frontend/specs/components/main/UserHeader.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/Header.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/UserContainer.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/UserHeader.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/index.ts
Labels: PR status: code ready

#2744 perf(concert-ticket-booking-frontend): modify input style on light theme
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/VerifyOtp.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/VerifyOtpLight.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/VerifyOtpTimer.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/PasswordRecovery.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/RecoveryEmail.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/VerifyOtp.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/VerifyOtpTimer.tsx
  libs/shadcn/src/lib/ui/input-otp.tsx
Labels: PR status: code ready

#2747 2682 fe post hover
  apps/L1AB/Instagram/instagram-frontend/specs/components/PostCardLikeSection.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/ProfilePostsSection.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCardLikeSection.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePageFirstPost.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePagePosts.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePostsSection.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/providers/StoryProvider.tsx
Labels: PR status: code ready

#2746 fix(ticket-booking): admin theme fix
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AddArtistComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AddEventComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AdminDashboardSearcher.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/ArtistComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/CancelComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/DatePickerWithRange.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/UpdateEventComponent.tsx
Labels: PR status: code ready

#2750 2745 be modify send qr to email template
  apps/L1AB/concert-ticket-booking/backend/specs/resolvers/mutations/booking/send-qr-to-email.spec.ts
  apps/L1AB/concert-ticket-booking/backend/src/library/nodemailer.ts
  apps/L1AB/concert-ticket-booking/backend/src/resolvers/mutations/booking/send-qr-to-email.ts
Labels: PR status: code ready

#2752 feat(concert-ticket-booking-frontend): merge payment detail button
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/Payment.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/Payment.tsx
Labels: PR status: code ready

#2755 feat(concert-ticket-booking frontend): skeleton added
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/BookTicket.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/BookTicket.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/Skeletons/BookTicketSkeleton.tsx
Labels: PR status: code ready

#2756 feat(hotel-booking-frontend): make signUpForm
  apps/L1AB/hotel-booking/backend/specs/resolvers/mutations/user/sign-up-check-otp.spec.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/mutations/user/index.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/mutations/user/sign-up-check-otp.ts
  apps/L1AB/hotel-booking/frontend/specs/components/main/SignUpForm.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/SignUpFormEmailStep.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/SignUpFormEmailStepPart1.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/SignUpFormEmailStepPart2.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/SignUpFormOtpStep.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/SignUpFormOtpStepPart1.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/SignUpFormOtpStepPart2.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/SignUpFormPasswordStep.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/SignUpFormPasswordStepPart1.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/SignUpFormPasswordStepPart2.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/app/layout.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/SignUpForm.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/SignUpFormEmailStep.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/SignUpFormOtpStep.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/SignUpFormPasswordStep.tsx
  apps/L1AB/hotel-booking/frontend/src/graphql/user.graphql
Labels: PR status: code ready

#2759 feat(ig-fe): zasav
  apps/L1AB/Instagram/instagram-backend/src/models/user-model.ts
  apps/L1AB/Instagram/instagram-frontend/specs/components/PostCard.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/LeftSideBar.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCard.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostDetail.tsx
Labels: PR status: code ready

#2766 feat(tinder): be setup
  apps/L1E/tinder/tinder-be/src/types/index.d.ts
  apps/L1E/tinder/tinder-be/tsconfig.json
Labels: PR status: code ready

#2770 2765 be set up
  apps/L1E/tinder/tinder-be/project.json
  apps/L1E/tinder/tinder-be/src/handler.ts
  apps/L1E/tinder/tinder-fe/codegen.ts
  apps/L1E/tinder/tinder-fe/cypress/e2e/render-all.pages.cy.tsx
  apps/L1E/tinder/tinder-fe/cypress/support/commands.ts
  apps/L1E/tinder/tinder-fe/cypress/utils/all-pages.json
  apps/L1E/tinder/tinder-fe/cypress/utils/intercept-graphql.ts
  apps/L1E/tinder/tinder-fe/next.config.js
  apps/L1E/tinder/tinder-fe/project.json
  apps/L1E/tinder/tinder-fe/public/TinderLogo-2017 2.png
  apps/L1E/tinder/tinder-fe/public/backround.png
  apps/L1E/tinder/tinder-fe/src/app/page.tsx
  apps/L1E/tinder/tinder-fe/src/components/Header.tsx
  apps/L1E/tinder/tinder-fe/src/components/providers/ApolloWrapper.tsx
  apps/L1E/tinder/tinder-fe/tsconfig.json
Labels: PR status: code ready, frontend

#2774 feat(tinder): testing
  apps/L1E/tinder/tinder-fe/src/app/page.tsx
Labels: PR status: code ready, frontend

#2778 feat(hrms): init
  apps/L1E/hrms/hrms-be/project.json
  apps/L1E/hrms/hrms-fe/project.json
  apps/L1E/hrms/hrms-fe/src/components/providers/ApolloWrapper.tsx
  apps/L1E/hrms/hrms-fe/tsconfig.json
Labels: PR status: code ready, backend

#2786 feat(hotel-booking-frontend): improve the signIn component
  apps/L1AB/hotel-booking/frontend/specs/components/main/SignInForm.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/SignInForm.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/SignUpFormEmailStep.tsx
  apps/L1AB/hotel-booking/frontend/src/components/providers/Auth.Provider.tsx
Labels: PR status: code ready, frontend

#2783 2765 be set up
  apps/L1E/tinder/tinder-fe/public/TinderLogo-2017 2.png
  apps/L1E/tinder/tinder-fe/public/fl.png
  apps/L1E/tinder/tinder-fe/public/hl.png
  apps/L1E/tinder/tinder-fe/public/redlogo.png
  apps/L1E/tinder/tinder-fe/specs/components/Addpassword.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Confirm.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Confirmsignup.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Footer.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/ForgetPassword.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Header.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/LoginHeader.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Main.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Matches.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Setnewpassword.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Signin.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Signup.spec.tsx
  apps/L1E/tinder/tinder-fe/src/app/chat/page.tsx
  apps/L1E/tinder/tinder-fe/src/app/forgetpassword/page.tsx
  apps/L1E/tinder/tinder-fe/src/app/global.css
  apps/L1E/tinder/tinder-fe/src/app/page.tsx
  apps/L1E/tinder/tinder-fe/src/app/signin/page.tsx
  apps/L1E/tinder/tinder-fe/src/app/signup/page.tsx
  apps/L1E/tinder/tinder-fe/src/components/Footer.tsx
  apps/L1E/tinder/tinder-fe/src/components/Header.tsx
  apps/L1E/tinder/tinder-fe/src/components/LoggedinHeader.tsx
  apps/L1E/tinder/tinder-fe/src/components/Matches.tsx
  apps/L1E/tinder/tinder-fe/src/components/chat/Main.tsx
  apps/L1E/tinder/tinder-fe/src/components/chat/MainChat.tsx
  apps/L1E/tinder/tinder-fe/src/components/forgetpassword/Confirm.tsx
  apps/L1E/tinder/tinder-fe/src/components/forgetpassword/Forgetpassword.tsx
  apps/L1E/tinder/tinder-fe/src/components/forgetpassword/Setnewpassword.tsx
  apps/L1E/tinder/tinder-fe/src/components/signin/Signin.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/Addpassword.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/Confirmsignup.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/Signup.tsx
  libs/shadcn/src/lib/ui/input-otp.tsx
Labels: PR status: code ready, frontend

#2789 feat(ig-be): get suggested users
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/user/get-suggeted-users-query.spec.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/user/get-suggested-users-query.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/user/index.ts
  apps/L1AB/Instagram/instagram-backend/src/schemas/user-schema.ts
Labels: PR status: code ready

#2792 feat(concert-ticket): demo page added
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/DemoHero.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/Event1.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/app/(main)/demo/page.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/democomponents/DemoMainHero.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/democomponents/Event1.tsx
Labels: PR status: code ready

#2795 feat(demo status): demo
  apps/L1AB/concert-ticket-booking/backend/src/models/event-model.ts
Labels: PR status: code ready

#2793 2775 fe sign up user detail informations
  apps/L1E/tinder/tinder-fe/specs/components/Date-of-birth.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Done.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Input-Form.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Interest.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Select.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Tinder.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Title.spec.tsx
  apps/L1E/tinder/tinder-fe/src/app/global.css
  apps/L1E/tinder/tinder-fe/src/app/mkae/page.tsx
  apps/L1E/tinder/tinder-fe/src/app/page.tsx
  apps/L1E/tinder/tinder-fe/src/app/register/page.tsx
  apps/L1E/tinder/tinder-fe/src/components/Logo.tsx
  apps/L1E/tinder/tinder-fe/src/components/UserDetails/DateOfBirth.tsx
  apps/L1E/tinder/tinder-fe/src/components/UserDetails/Done.tsx
  apps/L1E/tinder/tinder-fe/src/components/UserDetails/InterestSelect.tsx
  apps/L1E/tinder/tinder-fe/src/components/UserDetails/Select.tsx
  apps/L1E/tinder/tinder-fe/src/components/mkae/InputForm.tsx
  apps/L1E/tinder/tinder-fe/src/components/mkae/Test.tsx
  apps/L1E/tinder/tinder-fe/src/components/mkae/Tinder2024.tsx
  apps/L1E/tinder/tinder-fe/src/components/mkae/Title.tsx
  apps/L1E/tinder/tinder-fe/tsconfig.json
  libs/shadcn/src/lib/ui/button.tsx
Labels: PR status: code ready, frontend

#2801 feat(tinder): user information
  apps/L1E/tinder/tinder-fe/specs/components/UserInfo.spec.tsx
  apps/L1E/tinder/tinder-fe/src/app/mkae/page.tsx
  apps/L1E/tinder/tinder-fe/src/app/register/page.tsx
  apps/L1E/tinder/tinder-fe/src/components/UserDetails/UserInformation.tsx
Labels: PR status: code ready, frontend

#2802 feat(tinder): schema
  apps/L1E/tinder/tinder-be/src/models/user.model.ts
  apps/L1E/tinder/tinder-be/src/schemas/index.ts
  apps/L1E/tinder/tinder-be/src/schemas/user.schema.ts
  apps/L1E/tinder/tinder-fe/project.json
  apps/L1E/tinder/tinder-fe/specs/components/Signup.spec.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/Signup.tsx
Labels: PR status: code ready, backend

#2785 2781 fe requestform component
  apps/L1E/hrms/hrms-fe/jest.config.ts
  apps/L1E/hrms/hrms-fe/specs/components/RequestForm.spec.tsx
  apps/L1E/hrms/hrms-fe/specs/components/RequestFormPaid.spec.tsx
  apps/L1E/hrms/hrms-fe/specs/components/RequestFormRemote.spec.tsx
  apps/L1E/hrms/hrms-fe/specs/components/RequestFormcom.spec.tsx
  apps/L1E/hrms/hrms-fe/specs/components/RequestFormcom1.spec.tsx
  apps/L1E/hrms/hrms-fe/specs/components/RequestFormtime.spec.tsx
  apps/L1E/hrms/hrms-fe/specs/components/RequestSchema.spec.tsx
  apps/L1E/hrms/hrms-fe/specs/components/RequestSchemaDay.spec.tsx
  apps/L1E/hrms/hrms-fe/specs/components/Successmodal.spec.tsx
  apps/L1E/hrms/hrms-fe/src/app/page.tsx
  apps/L1E/hrms/hrms-fe/src/components/RequestForm.tsx
  apps/L1E/hrms/hrms-fe/src/components/requestForm/RequestFormPaid.tsx
  apps/L1E/hrms/hrms-fe/src/components/requestForm/RequestFormRemote.tsx
  apps/L1E/hrms/hrms-fe/src/components/requestForm/RequestFormcom.tsx
  apps/L1E/hrms/hrms-fe/src/components/requestForm/RequestFormcom1.tsx
  apps/L1E/hrms/hrms-fe/src/components/requestForm/RequestFormtime.tsx
  apps/L1E/hrms/hrms-fe/src/components/requestForm/RequestSchema.tsx
  apps/L1E/hrms/hrms-fe/src/components/requestForm/RequestSchemaDay.tsx
  apps/L1E/hrms/hrms-fe/src/components/requestForm/Successmodal.tsx
Labels: PR status: code ready, frontend

#2805 feat(tinder): hhe
  apps/L1E/tinder/tinder-fe/project.json
  apps/L1E/tinder/tinder-fe/specs/components/DateOfBirth.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Interests.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/ProfilePage.spec.tsx
  apps/L1E/tinder/tinder-fe/src/app/profile/page.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/Bio.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/DateOfBirth.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/GenderPreference.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/Interests.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/LeftSideBar.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/MainSection.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/PersonalInfo.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/Profile.tsx
Labels: PR status: code ready, frontend

#2808 feat(tinder): sandbox
  apps/L1E/tinder/tinder-be/specs/resolvers/mutations/createuser.spec.ts
  apps/L1E/tinder/tinder-be/src/models/user.model.ts
  apps/L1E/tinder/tinder-be/src/resolvers/mutations/create-user.ts
  apps/L1E/tinder/tinder-be/src/resolvers/mutations/index.ts
  apps/L1E/tinder/tinder-be/src/schemas/user.schema.ts
  apps/L1E/tinder/tinder-fe/specs/components/Addpassword.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Confirmsignup.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Signup.spec.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/Addpassword.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/Confirmsignup.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/Signup.tsx
  apps/L1E/tinder/tinder-fe/src/graphql/all.graphql
Labels: PR status: code ready, backend, frontend

#2807 feat(tinder): upload image comp
  apps/L1E/tinder/tinder-fe/specs/components/Date-of-birth.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/DateOfBirth.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/common/Done.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/common/InputForm.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/common/Tinder.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/common/Title.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/users/DateOfBirth.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/users/ImageUpload.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/users/Interest.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/users/Select.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/users/UserInformation.spec.tsx
  apps/L1E/tinder/tinder-fe/src/app/register/page.tsx
  apps/L1E/tinder/tinder-fe/src/components/common/Done.tsx
  apps/L1E/tinder/tinder-fe/src/components/common/InputForm.tsx
  apps/L1E/tinder/tinder-fe/src/components/common/Logo.tsx
  apps/L1E/tinder/tinder-fe/src/components/common/Tinder.tsx
  apps/L1E/tinder/tinder-fe/src/components/common/Title.tsx
  apps/L1E/tinder/tinder-fe/src/components/mkae/Test.tsx
  apps/L1E/tinder/tinder-fe/src/components/mkae/Tinder2024.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/DateOfBirth.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/Profile.tsx
  apps/L1E/tinder/tinder-fe/src/components/users/DateOfBirth.tsx
  apps/L1E/tinder/tinder-fe/src/components/users/ImageUpload.tsx
  apps/L1E/tinder/tinder-fe/src/components/users/InterestSelect.tsx
  apps/L1E/tinder/tinder-fe/src/components/users/Select.tsx
  apps/L1E/tinder/tinder-fe/src/components/users/UserInformation.tsx
  apps/L1E/tinder/tinder-fe/tsconfig.json
Labels: PR status: code ready, frontend

#2814 feat(ig-fe): suggested users hiiv
  apps/L1AB/Instagram/instagram-frontend/specs/components/SuggestCard.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/UsersMap.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCard.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/SuggestCard.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/UsersMap.tsx
  apps/L1AB/Instagram/instagram-frontend/src/graphql/all.graphql
Labels: PR status: code ready

#2811 feat(tinder): done icon svg
  apps/L1E/tinder/tinder-fe/specs/components/common/DoneIcon.spec.tsx
  apps/L1E/tinder/tinder-fe/src/components/common/Done.tsx
  apps/L1E/tinder/tinder-fe/src/components/common/DoneIcon.tsx
  apps/L1E/tinder/tinder-fe/src/components/common/Logo.tsx
Labels: PR status: code ready, frontend

#2817 feat(tinder): user created
  apps/L1E/tinder/tinder-be/specs/resolvers/mutations/createuser.spec.ts
  apps/L1E/tinder/tinder-be/src/resolvers/mutations/create-user.ts
  apps/L1E/tinder/tinder-be/src/resolvers/mutations/index.ts
  apps/L1E/tinder/tinder-be/src/resolvers/mutations/user/create-user.ts
  apps/L1E/tinder/tinder-be/src/resolvers/mutations/user/index.ts
  apps/L1E/tinder/tinder-be/src/resolvers/queries/index.ts
  apps/L1E/tinder/tinder-be/src/resolvers/queries/user/get-user-by-id.ts
  apps/L1E/tinder/tinder-be/src/resolvers/queries/user/index.ts
  apps/L1E/tinder/tinder-fe/next.config.js
  apps/L1E/tinder/tinder-fe/specs/components/Addpassword.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/Signup.spec.tsx
  apps/L1E/tinder/tinder-fe/src/components/providers/ApolloWrapper.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/Addpassword.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/Signup.tsx
Labels: PR status: code ready, backend, frontend

#2824 feat(hotel-booking-frontend): cancel booking
  apps/L1AB/hotel-booking/frontend/specs/components/main/CancelBooking.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/CancelBookingDialog.tsx
Labels: PR status: code ready

#2825 feat(be story): story delete
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/mutations/story/delete-story.spec.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/story/delete-story.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/story/index.ts
  apps/L1AB/Instagram/instagram-backend/src/schemas/story.schema.ts
Labels: PR status: code ready

#2826 feat(tinder): add profile page
  apps/L1E/tinder/tinder-fe/specs/components/Date.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/LeftSideBar.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/ProfilePage.spec.tsx
  apps/L1E/tinder/tinder-fe/src/app/libgun/page.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/Date.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/ImagesSection.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/LeftSideBar.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/MainSection.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/Profile.tsx
  apps/L1E/tinder/tinder-fe/src/components/profile/ProfileInputForm.tsx
Labels: PR status: code ready, frontend

#2831 feat(ig-be): createpost mutation zasav
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/mutations/post/create-post.spec.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/post/create-post.ts
  apps/L1AB/Instagram/instagram-backend/src/schemas/posts.schema.ts
Labels: PR status: code ready

#2830 feat(hrms): fe-myrequest
  apps/L1E/hrms/hrms-fe/specs/components/Leave.spec.tsx
  apps/L1E/hrms/hrms-fe/specs/components/LeaveCalendar.spec.tsx
  apps/L1E/hrms/hrms-fe/specs/components/MyRequest.spec.tsx
  apps/L1E/hrms/hrms-fe/specs/components/PaidLeave.spec.tsx
  apps/L1E/hrms/hrms-fe/specs/components/RemoteWork.spec.tsx
  apps/L1E/hrms/hrms-fe/specs/components/RequestSchema.spec.tsx
  apps/L1E/hrms/hrms-fe/specs/components/RequestStory.spec.tsx
  apps/L1E/hrms/hrms-fe/src/components/Leave.tsx
  apps/L1E/hrms/hrms-fe/src/components/LeaveCalendar.tsx
  apps/L1E/hrms/hrms-fe/src/components/MyRequest.tsx
  apps/L1E/hrms/hrms-fe/src/components/PaidLeave.tsx
  apps/L1E/hrms/hrms-fe/src/components/RemoteWork.tsx
  apps/L1E/hrms/hrms-fe/src/components/RequestStory.tsx
Labels: PR status: code ready, frontend

#2836 feat(ig-fe): graphql zasav
  apps/L1AB/Instagram/instagram-frontend/src/graphql/mutation.graphql
Labels: PR status: code ready

#2841 feat: bE get-me-query
  apps/L1AB/hotel-booking/backend/specs/resolvers/mutations/user/sign-in.spec.ts
  apps/L1AB/hotel-booking/backend/specs/resolvers/queries/amenity/get-amenities.spec.ts
  apps/L1AB/hotel-booking/backend/specs/resolvers/queries/user/get-me.spec.ts
  apps/L1AB/hotel-booking/backend/src/handler.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/mutations/user/sign-in.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/queries/user/get-me.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/queries/user/index.ts
  apps/L1AB/hotel-booking/backend/src/schemas/user.schema.ts
  apps/L1AB/hotel-booking/backend/src/types/index.d.ts
Labels: PR status: code ready

#2842 feat(hotel-booking-frontend): create room
  apps/L1AB/hotel-booking/frontend/specs/components/admin/RoomDetails.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/assets/GeneralInfoDialog.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/assets/hotel-details/HotelDetailsImages.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/assets/hotel-details/HotelDetailsRoomTypes.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/admin/assets/room-details/RoomDetailsGeneralInfo.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/GuestInfo.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/HotelDetails.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/RoomDetails.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/DetailsContainer.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/hotel-details/HotelDetailsImages.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/hotel-details/HotelDetailsRoomTypes.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/assets/room-details/RoomDetailsGeneralInfo.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/dialogs/GeneralInfoDialog.tsx
  apps/L1AB/hotel-booking/frontend/src/components/providers/AdminProvider.tsx
  apps/L1AB/hotel-booking/frontend/src/components/providers/utils/Validations.tsx
Labels: PR status: code ready

#2833 feat(tinder): carousel
  apps/L1E/tinder/tinder-fe/specs/components/match/carousel.spec.tsx
  apps/L1E/tinder/tinder-fe/src/app/match-zone/page.tsx
  apps/L1E/tinder/tinder-fe/src/components/match/Carousel.tsx
Labels: PR status: code ready, frontend

#2840 feat(hotel-booking-frontend): add booking details
  apps/L1AB/hotel-booking/frontend/specs/components/main/BookedComponent.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/BookingDetailRoom.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/BookingDetails.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/UserProfile.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/app/(main)/bookings/[bookingId]/page.tsx
  apps/L1AB/hotel-booking/frontend/src/app/(main)/bookings/[booking]/page.tsx
  apps/L1AB/hotel-booking/frontend/src/app/(main)/bookings/cancelBooking/page.tsx
  apps/L1AB/hotel-booking/frontend/src/app/(main)/bookings/previousBooking/page.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/BookedComponent.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/BookingCard.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/BookingDetailBooked.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/BookingDetailRoom.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/BookingDetails.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/CancelBookingDialog.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/ConfirmedBooking.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/assets/CheckInDialog.tsx
Labels: PR status: code ready

#2849 feat(tinder): users match fe
  apps/L1E/tinder/tinder-fe/cypress/utils/all-pages.json
  apps/L1E/tinder/tinder-fe/specs/components/match/carousel.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/match/userMatch.spec.tsx
  apps/L1E/tinder/tinder-fe/src/app/match-zone/page.tsx
  apps/L1E/tinder/tinder-fe/src/components/match/Carousel.tsx
  apps/L1E/tinder/tinder-fe/src/components/match/UserMatchComp.tsx
Labels: PR status: code ready, frontend

#2843 feat(hrms): be
  apps/L1E/hrms/hrms-be/next.config.js
  apps/L1E/hrms/hrms-be/specs/resolvers/mutations/create-Employee.spec.ts
  apps/L1E/hrms/hrms-be/specs/resolvers/mutations/create-Request.spec.ts
  apps/L1E/hrms/hrms-be/specs/resolvers/mutations/delete-Employee.spec.ts
  apps/L1E/hrms/hrms-be/specs/resolvers/mutations/update-Employee.spec.ts
  apps/L1E/hrms/hrms-be/src/models/employee.model.ts
  apps/L1E/hrms/hrms-be/src/models/index.ts
  apps/L1E/hrms/hrms-be/src/models/request.model.ts
  apps/L1E/hrms/hrms-be/src/resolvers/mutations/employee/create-employee.ts
  apps/L1E/hrms/hrms-be/src/resolvers/mutations/employee/delete-employee.ts
  apps/L1E/hrms/hrms-be/src/resolvers/mutations/employee/index.ts
  apps/L1E/hrms/hrms-be/src/resolvers/mutations/employee/update-employee.ts
  apps/L1E/hrms/hrms-be/src/resolvers/mutations/index.ts
  apps/L1E/hrms/hrms-be/src/resolvers/mutations/requests/create-request.ts
  apps/L1E/hrms/hrms-be/src/resolvers/mutations/requests/index.ts
  apps/L1E/hrms/hrms-be/src/schemas/employee.schema.ts
  apps/L1E/hrms/hrms-be/src/schemas/index.ts
  apps/L1E/hrms/hrms-be/src/schemas/requests.schema.ts
Labels: PR status: code ready, backend

#2851 feat(demo): demo frontend
  apps/L1AB/concert-ticket-booking/frontend/specs/components/adminspecs/AdminDashboardContainer.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/adminspecs/AdminNavbar.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/adminspecs/DemoComponent.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/DemoHero.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/Event1.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/app/admin/demo/page.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/AdminNavbar.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/admincomponents/DemoComponent.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/democomponents/DemoMainHero.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/democomponents/Event1.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/graphql/event.graphql
Labels: PR status: code ready

#2856 feat(tinder): pics
  apps/L1E/tinder/tinder-fe/public/bla.jpg
  apps/L1E/tinder/tinder-fe/public/rokitbay.jpg
  apps/L1E/tinder/tinder-fe/src/components/match/Carousel.tsx
Labels: PR status: code ready, frontend

#2858 2857 loading screen
  apps/L1E/tinder/tinder-fe/specs/components/common/Loading.spec.tsx
  apps/L1E/tinder/tinder-fe/src/app/match/page.tsx
  apps/L1E/tinder/tinder-fe/src/components/Loading.tsx
Labels: PR status: code ready, frontend

#2862 feat(ig-fe): ooriin post-g harah
  apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/post/create-post.ts
  apps/L1AB/Instagram/instagram-frontend/specs/components/NewsFeed.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/PostCard.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/CreatePost.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/CreatePostDescription.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/NewsFeed.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCard.tsx
  apps/L1AB/Instagram/instagram-frontend/src/graphql/post.graphql
Labels: PR status: code ready

#2864 feat(ig-fe): leftside bar zasav
  apps/L1AB/Instagram/instagram-frontend/specs/components/NavigationLink.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/CreateButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/HomeButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/InstagramButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/InstagramLogo.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/LeftSideBar.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/LogoutButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/MoreButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/NavigationLink.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/NotificationDrawer.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCardLikeSection.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/SearchButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/SearchDrawer.tsx
Labels: PR status: code ready, frontend

#2865 feat(tinder): stepper
  apps/L1E/tinder/tinder-be/specs/resolvers/mutations/createuser.spec.ts
  apps/L1E/tinder/tinder-be/src/models/user.model.ts
  apps/L1E/tinder/tinder-be/src/resolvers/mutations/user/create-user.ts
  apps/L1E/tinder/tinder-be/src/schemas/user.schema.ts
  apps/L1E/tinder/tinder-fe/codegen.ts
  apps/L1E/tinder/tinder-fe/project.json
  apps/L1E/tinder/tinder-fe/specs/components/Addpassword.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/home/Miain.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/users/DateOfBirth.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/users/ImageUpload.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/users/Interest.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/users/Select.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/users/UserInformation.spec.tsx
  apps/L1E/tinder/tinder-fe/src/app/home/page.tsx
  apps/L1E/tinder/tinder-fe/src/app/page.tsx
  apps/L1E/tinder/tinder-fe/src/app/register/page.tsx
  apps/L1E/tinder/tinder-fe/src/components/common/InputForm.tsx
  apps/L1E/tinder/tinder-fe/src/components/home/Main.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/Addpassword.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/DateOfBirth.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/ImageUpload.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/InterestSelect.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/Signup.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/Test.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/UserInformation.tsx
  apps/L1E/tinder/tinder-fe/src/components/users/DateOfBirth.tsx
  apps/L1E/tinder/tinder-fe/src/components/users/ImageUpload.tsx
  apps/L1E/tinder/tinder-fe/src/components/users/InterestSelect.tsx
  apps/L1E/tinder/tinder-fe/src/components/users/Select.tsx
  apps/L1E/tinder/tinder-fe/src/components/users/UserInformation.tsx
Labels: PR status: code ready, backend, frontend

#2870 feat(ig-[fe]): jjig fixes
  apps/L1AB/Instagram/instagram-frontend/src/components/LogoutButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCardLikeSection.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePostsSection.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/SuggestCard.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/UsersMap.tsx
Labels: PR status: code ready

#2872 feat(tinder): loader hiilee
  apps/L1E/tinder/tinder-fe/specs/components/LoaderSpinner.spec.tsx
  apps/L1E/tinder/tinder-fe/src/components/LoaderSpinner.tsx
Labels: PR status: code ready, frontend

#2873 2630 fe search by date and traveller
  apps/L1AB/hotel-booking/backend/specs/resolvers/queries/room/get-available-rooms.spec.ts
  apps/L1AB/hotel-booking/backend/src/resolvers/queries/room/get-available-rooms.ts
  apps/L1AB/hotel-booking/backend/src/schemas/amenity.schema.ts
  apps/L1AB/hotel-booking/backend/src/schemas/hotel.schema.ts
  apps/L1AB/hotel-booking/backend/src/schemas/room.schema.ts
  apps/L1AB/hotel-booking/frontend/specs/components/main/Search.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/assets/SearchDatePicker.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/app/layout.tsx
  apps/L1AB/hotel-booking/frontend/src/components/icon/CalendarIcon.tsx
  apps/L1AB/hotel-booking/frontend/src/components/icon/index.ts
  apps/L1AB/hotel-booking/frontend/src/components/main/Search.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/assets/SearchDatePicker.tsx
  apps/L1AB/hotel-booking/frontend/src/components/providers/MainProvider.tsx
  apps/L1AB/hotel-booking/frontend/src/graphql/room.graphql
Labels: PR status: code ready

#2874 feat(ig-fe): story delete
  apps/L1AB/Instagram/instagram-frontend/specs/components/UserStory.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/UserStory.tsx
  apps/L1AB/Instagram/instagram-frontend/src/graphql/story.graphql
Labels: PR status: code ready

#2878 feat(ig-be): story
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/story/get-all-stories.spec.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/story/get-all-stories.ts
  apps/L1AB/Instagram/instagram-backend/src/schemas/story.schema.ts
Labels: PR status: code ready

#2846 feat(hotel-booking-frontend): push to admin/hotels
  apps/L1AB/hotel-booking/frontend/src/components/providers/Auth.Provider.tsx
Labels: PR status: code ready, frontend

#2880 feat(tinder): folder structure
  apps/L1E/tinder/tinder-be/specs/resolvers/mutations/createuser.spec.ts
  apps/L1E/tinder/tinder-be/src/models/user/user.model.ts
  apps/L1E/tinder/tinder-be/src/resolvers/mutations/user/create-user.ts
  apps/L1E/tinder/tinder-fe/specs/components/chat/Main.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/chat/Matches.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/common/Loading.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/forgetpassword/Confirm.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/forgetpassword/ForgetPassword.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/forgetpassword/Setnewpassword.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/main/Footer.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/main/Header.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/main/LoaderSpinner.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/main/LoginHeader.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/profile/Date.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/profile/Interests.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/profile/LeftSideBar.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/profile/ProfilePage.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/signin/Signin.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/signup/Addpassword.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/signup/Confirmsignup.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/signup/DateOfBirth.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/signup/ImageUpload.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/signup/Interest.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/signup/Select.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/signup/Signup.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/signup/UserInformation.spec.tsx
  apps/L1E/tinder/tinder-fe/src/app/global.css
  apps/L1E/tinder/tinder-fe/src/app/match/page.tsx
  apps/L1E/tinder/tinder-fe/src/app/page.tsx
  apps/L1E/tinder/tinder-fe/src/components/chat/Main.tsx
  apps/L1E/tinder/tinder-fe/src/components/chat/Matches.tsx
  apps/L1E/tinder/tinder-fe/src/components/main/Footer.tsx
  apps/L1E/tinder/tinder-fe/src/components/main/Header.tsx
  apps/L1E/tinder/tinder-fe/src/components/main/LoaderSpinner.tsx
  apps/L1E/tinder/tinder-fe/src/components/main/Loading.tsx
  apps/L1E/tinder/tinder-fe/src/components/main/LoggedinHeader.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/InterestSelect.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/Select.tsx
Labels: PR status: code ready, backend, frontend

#2883 revert(tindr): cloudinary
  apps/L1E/tinder/tinder-fe/specs/components/home/Main.spec.tsx
  apps/L1E/tinder/tinder-fe/specs/components/signup/ImageUpload.spec.tsx
  apps/L1E/tinder/tinder-fe/src/app/home/page.tsx
  apps/L1E/tinder/tinder-fe/src/app/layout.tsx
  apps/L1E/tinder/tinder-fe/src/components/signup/ImageUpload.tsx
Labels: PR status: code ready, frontend

#2888 feat: fe get me query
  apps/L1AB/hotel-booking/backend/specs/resolvers/queries/user/get-me.spec.ts
  apps/L1AB/hotel-booking/backend/specs/resolvers/queries/user/get-me.spec.tsx
  apps/L1AB/hotel-booking/backend/src/resolvers/queries/user/get-me.ts
  apps/L1AB/hotel-booking/backend/src/types/index.d.ts
  apps/L1AB/hotel-booking/frontend/specs/components/main/MainHeader.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/UserContainer.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/MainHeader.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/UserContainer.tsx
  apps/L1AB/hotel-booking/frontend/src/components/providers/ApolloWrapper.tsx
  apps/L1AB/hotel-booking/frontend/src/components/providers/Auth.Provider.tsx
Labels: PR status: code ready

#2891 feat(ig fe): story
  apps/L1AB/Instagram/instagram-frontend/src/components/UserStory.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/providers/StoryProvider.tsx
  apps/L1AB/Instagram/instagram-frontend/src/graphql/story.graphql
Labels: PR status: code ready

#2893 feat: fe signed user info header
  apps/L1AB/hotel-booking/frontend/specs/components/main/Header.spec.tsx
  apps/L1AB/hotel-booking/frontend/specs/components/main/UserSettings.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/Header.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/UserContainer.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/UserSettings.tsx
Labels: PR status: code ready

#2897 feat(fe darkmode): darkmode duussan
  apps/L1AB/Instagram/instagram-frontend/specs/components/DarkMode.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/specs/components/LightMode.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/(main)/layout.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/layout.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/CreateButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/CreatePost.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/DarkMode.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/EditProfile.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/FollowersDialog.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/FollowersDialogRemove.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/FollowingButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/HomeButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/InstagramButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/LeftSideBar.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/LogoutButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/MoreButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/NavigationLink.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/NewsFeed.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/NotificationButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/NotificationDrawer.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCardCommentSection.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCardLikeSection.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostDetail.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePagePosts.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePagePostsAndSaved.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePageTop.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/RemoveFollowersDialog.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/RightSideBar.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/SearchButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/SearchDrawer.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/StoryCard.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/SuggestCard.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/UserStory.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/UsersMap.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/notificationComps/EarlierNotifications.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/notificationComps/TodayNotifications.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/notificationComps/YesterdayNotifications.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/providers/ApolloWrapper.tsx
Labels: PR status: code ready

#2896 feat(ig-be): getallstories query
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/story/get-all-stories.spec.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/story/get-all-stories.ts
Labels: PR status: code ready

#2901 feat(ig-fe): jijig fixes
  apps/L1AB/Instagram/instagram-frontend/src/app/(main)/home/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/app/(main)/profile/page.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/LogoutButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/MoreButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/NewsFeed.tsx
Labels: PR status: code ready

#2876 feat(event model): model
  apps/L1AB/concert-ticket-booking/backend/src/models/event-model.ts
Labels: PR status: code ready

#2900 feat: fe sign out profile
  apps/L1AB/hotel-booking/frontend/specs/components/main/UserProfile.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/Header.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/MainHeader.tsx
  apps/L1AB/hotel-booking/frontend/src/components/main/UserProfile.tsx
Labels: PR status: code ready

#2904 feat(concert-ticket-booking): add ddemo oage
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/MainNavbar.spec.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/democomponents/DemoMainHero.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/MainNavbar.tsx
Labels: PR status: code ready

#2906 feat(fe-ig): story
  apps/L1AB/Instagram/instagram-frontend/specs/components/PostCard.spec.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/CreateStory.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/PostCard.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/UserStory.tsx
Labels: PR status: code ready

#2910 feat(concert-ticket-frontend): added
  apps/L1AB/concert-ticket-booking/frontend/specs/components/mainspecs/mock.ts
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/EventDetails.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/RelatedEvents.tsx
  apps/L1AB/concert-ticket-booking/frontend/src/components/maincomponents/StageStyle.tsx
Labels: PR status: code ready

#2909 feat: zassan
  apps/L1AB/Instagram/instagram-frontend/src/components/DarkMode.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/HomeButton.tsx
  apps/L1AB/Instagram/instagram-frontend/src/components/NavigationLink.tsx
Labels: PR status: code ready

#2911 feat(ig-[be]): getposts query
  apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/post/get-posts-by-followers-id.spec.ts
  apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/post/get-posts-by-followers-id.ts
Labels: PR status: code ready

#2913 refactor(hotel-booking-frontend): refactor guests table ui
  apps/L1AB/hotel-booking/frontend/specs/components/admin/GuestsTable.spec.tsx
  apps/L1AB/hotel-booking/frontend/src/components/admin/GuestsTable.tsx
Labels: PR status: code ready

#2914 feat(fe-ig): story
  apps/L1AB/Instagram/instagram-frontend/src/components/UserStory.tsx
Labels: PR status: code ready

#2916 feat(concert-ticket-booking backend): fixed
  apps/L1AB/concert-ticket-booking/backend/src/models/booking-model.ts
Labels: PR status: code ready
